/**
 * OpenTelemetry GenAI semantic convention attribute name constants.
 *
 * Sourced from: https://opentelemetry.io/docs/specs/semconv/gen-ai/
 * Spec version: v1.29.0 — Development status as of April 2026.
 *
 * All gen_ai.* names live here. A spec rename is a one-file diff.
 * Update SEMCONV_GEN_AI_VERSION when upgrading to a new spec version.
 */

// ---------------------------------------------------------------------------
// Version pin
// ---------------------------------------------------------------------------

/** Version of the OTel GenAI semconv these constants implement. */
export const SEMCONV_GEN_AI_VERSION = "1.29.0" as const;

// ---------------------------------------------------------------------------
// Required attributes (every span must include these)
// ---------------------------------------------------------------------------

/** The name of the operation: "chat", "execute_tool", "invoke_agent", etc. */
export const ATTR_GEN_AI_OPERATION_NAME = "gen_ai.operation.name" as const;

/** The name of the GenAI provider (e.g. "openai", "anthropic", "google"). */
export const ATTR_GEN_AI_PROVIDER_NAME = "gen_ai.provider.name" as const;

// ---------------------------------------------------------------------------
// Request attributes
// ---------------------------------------------------------------------------

/** Model requested by the caller (e.g. "gpt-4o", "claude-3-5-sonnet-20241022"). */
export const ATTR_GEN_AI_REQUEST_MODEL = "gen_ai.request.model" as const;

/** Sampling temperature for the request. */
export const ATTR_GEN_AI_REQUEST_TEMPERATURE = "gen_ai.request.temperature" as const;

/** Maximum number of tokens the model may generate. */
export const ATTR_GEN_AI_REQUEST_MAX_TOKENS = "gen_ai.request.max_tokens" as const;

// ---------------------------------------------------------------------------
// Response attributes
// ---------------------------------------------------------------------------

/** Model that actually served the response — may differ from requested model. */
export const ATTR_GEN_AI_RESPONSE_MODEL = "gen_ai.response.model" as const;

/** Provider-assigned response identifier. */
export const ATTR_GEN_AI_RESPONSE_ID = "gen_ai.response.id" as const;

/**
 * Array of finish reasons from the response (e.g. ["stop"], ["tool_use"]).
 * Stored as string[] attribute.
 */
export const ATTR_GEN_AI_RESPONSE_FINISH_REASONS = "gen_ai.response.finish_reasons" as const;

// ---------------------------------------------------------------------------
// Token usage attributes
// ---------------------------------------------------------------------------

/** Number of input/prompt tokens consumed by the request. */
export const ATTR_GEN_AI_USAGE_INPUT_TOKENS = "gen_ai.usage.input_tokens" as const;

/** Number of output/completion tokens generated by the response. */
export const ATTR_GEN_AI_USAGE_OUTPUT_TOKENS = "gen_ai.usage.output_tokens" as const;

// ---------------------------------------------------------------------------
// Tool attributes
// ---------------------------------------------------------------------------

/** Name of the tool called (matches the tool's registered name). */
export const ATTR_GEN_AI_TOOL_NAME = "gen_ai.tool.name" as const;

/** Provider-assigned identifier for this specific tool call invocation. */
export const ATTR_GEN_AI_TOOL_CALL_ID = "gen_ai.tool.call.id" as const;

// ---------------------------------------------------------------------------
// Agent attributes
// ---------------------------------------------------------------------------

/** Name of the agent (from AgentManifest.name or agentId). */
export const ATTR_GEN_AI_AGENT_NAME = "gen_ai.agent.name" as const;

// ---------------------------------------------------------------------------
// Operation name values
// ---------------------------------------------------------------------------

export const GEN_AI_OPERATION_CHAT = "chat" as const;
export const GEN_AI_OPERATION_EXECUTE_TOOL = "execute_tool" as const;
export const GEN_AI_OPERATION_INVOKE_AGENT = "invoke_agent" as const;

// ---------------------------------------------------------------------------
// Koi custom attributes (koi.* namespace — not part of OTel spec)
// ---------------------------------------------------------------------------

/** Koi session identifier — use to filter traces for a single session. */
export const ATTR_KOI_SESSION_ID = "koi.session.id" as const;

/** Step outcome as recorded in ATIF: "success" | "failure" | "retry". */
export const ATTR_KOI_STEP_OUTCOME = "koi.step.outcome" as const;

// ---------------------------------------------------------------------------
// Span event names (content capture — disabled by default)
// ---------------------------------------------------------------------------

/**
 * Span event for the user/human message sent to the model.
 * Only emitted when OtelMiddlewareConfig.captureContent is true.
 */
export const EVENT_GEN_AI_USER_MESSAGE = "gen_ai.user.message" as const;

/**
 * Span event for the model's response content.
 * Only emitted when OtelMiddlewareConfig.captureContent is true.
 */
export const EVENT_GEN_AI_CHOICE = "gen_ai.choice" as const;

// ---------------------------------------------------------------------------
// Metric names (koi custom)
// ---------------------------------------------------------------------------

/**
 * Histogram instrument name for per-call GenAI cost in USD.
 * Only recorded when RichTrajectoryStep.metrics.costUsd is present.
 */
export const METRIC_KOI_GEN_AI_COST = "koi.gen_ai.cost" as const;
