/**
 * Pattern-based permission classifier.
 *
 * Evaluates tool names against allow/deny/ask pattern rules with
 * named group expansion. Groups are expanded at construction time
 * (compile-once, validate-per-call).
 */

import type { ApprovalDecision, ApprovalRequest } from "@koi/core/middleware";
import type { PermissionBackend, PermissionDecision } from "@koi/core/permission-backend";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PermissionRules {
  readonly allow: readonly string[];
  readonly deny: readonly string[];
  readonly ask: readonly string[];
}

export interface PatternBackendConfig {
  /** Tool name patterns for allow/deny/ask decisions. */
  readonly rules: PermissionRules;
  /** Deny unmatched tools. Default: true (fail-closed). */
  readonly defaultDeny?: boolean;
  /** Named tool group expansions. Use `group:<name>` in rules. */
  readonly groups?: Readonly<Record<string, readonly string[]>>;
}

// ---------------------------------------------------------------------------
// Default groups
// ---------------------------------------------------------------------------

export const DEFAULT_GROUPS: Readonly<Record<string, readonly string[]>> = {
  fs: ["fs:*", "fs_*"],
  fs_read: [
    "fs:read",
    "fs:stat",
    "fs:list",
    "fs:glob",
    "fs_read",
    "fs_stat",
    "fs_list",
    "fs_search",
  ],
  fs_write: ["fs:write", "fs:create", "fs:mkdir", "fs_write", "fs_create", "fs_edit", "fs_mkdir"],
  fs_delete: ["fs:delete", "fs:rm", "fs:rmdir", "fs_delete", "fs_rm", "fs_rmdir"],
  runtime: ["exec", "spawn", "bash", "shell"],
  web: ["http:*", "fetch", "curl"],
  browser: ["browser_*"],
  db: ["db:*"],
  db_read: ["db:query", "db:read", "db:select"],
  db_write: ["db:write", "db:insert", "db:update", "db:delete"],
  lsp: ["lsp/*"],
  mcp: ["mcp/*"],
} as const;

// ---------------------------------------------------------------------------
// Structured default-deny flag (internal to package)
// ---------------------------------------------------------------------------

/**
 * Symbol-keyed property on deny decisions to distinguish default-deny from
 * explicit deny. Using a symbol prevents external backends from accidentally
 * or maliciously setting this flag via a string-keyed property.
 */
export const IS_DEFAULT_DENY: unique symbol = Symbol.for(
  "@koi/middleware-permissions/default-deny",
);

/** Check whether a deny decision was generated by the default-deny fallback. */
export function isDefaultDeny(decision: PermissionDecision): boolean {
  return (
    decision.effect === "deny" && (decision as Record<symbol, unknown>)[IS_DEFAULT_DENY] === true
  );
}

/** @deprecated Use IS_DEFAULT_DENY symbol instead. Kept for backward compat in reason text. */
export const DEFAULT_DENY_MARKER = "(default deny)";

// ---------------------------------------------------------------------------
// Pattern matching
// ---------------------------------------------------------------------------

function matchesPattern(toolId: string, pattern: string): boolean {
  if (pattern === "*") return true;
  if (pattern.endsWith("*")) {
    return toolId.startsWith(pattern.slice(0, -1));
  }
  return toolId === pattern;
}

function matchesAny(toolId: string, patterns: readonly string[]): boolean {
  return patterns.some((p) => matchesPattern(toolId, p));
}

function expandGroups(
  patterns: readonly string[],
  groups: Readonly<Record<string, readonly string[]>>,
): readonly string[] {
  const expanded: string[] = [];
  for (const pattern of patterns) {
    if (pattern.startsWith("group:")) {
      const groupName = pattern.slice(6);
      const groupPatterns = groups[groupName];
      if (groupPatterns !== undefined) {
        expanded.push(...groupPatterns);
      } else {
        // Unknown group — keep as literal pattern
        expanded.push(pattern);
      }
    } else {
      expanded.push(pattern);
    }
  }
  return expanded;
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

export function createPatternPermissionBackend(config: PatternBackendConfig): PermissionBackend {
  const groups = config.groups ?? {};
  const defaultDeny = config.defaultDeny ?? true;

  // Expand groups at construction time
  const denyPatterns = expandGroups(config.rules.deny, groups);
  const askPatterns = expandGroups(config.rules.ask, groups);
  const allowPatterns = expandGroups(config.rules.allow, groups);

  return {
    check(query) {
      const toolId = query.resource;

      // Deny-first evaluation
      if (matchesAny(toolId, denyPatterns)) {
        return { effect: "deny", reason: `Tool "${toolId}" is denied by policy` };
      }

      if (matchesAny(toolId, askPatterns)) {
        return { effect: "ask", reason: `Tool "${toolId}" requires approval` };
      }

      if (matchesAny(toolId, allowPatterns)) {
        return { effect: "allow" };
      }

      // No match — apply default
      if (defaultDeny) {
        const decision: PermissionDecision & Record<symbol, boolean> = {
          effect: "deny",
          reason: `Tool "${toolId}" not in allow list ${DEFAULT_DENY_MARKER}`,
          [IS_DEFAULT_DENY]: true,
        };
        return decision;
      }

      return { effect: "allow" };
    },
  };
}

// ---------------------------------------------------------------------------
// Auto-approval handler (testing/development)
// ---------------------------------------------------------------------------

export function createAutoApprovalHandler(): (
  request: ApprovalRequest,
) => Promise<ApprovalDecision> {
  return async (_request: ApprovalRequest): Promise<ApprovalDecision> => ({
    kind: "allow",
  });
}
