/**
 * Core types for the @koi/forge self-extension system.
 */

import type {
  BrickId,
  BrickKind,
  BrickLifecycle,
  BrickRequires,
  ContentMarker,
  DataClassification,
  ForgeScope,
  TestCase,
  ToolDescriptor,
  TrustTier,
} from "@koi/core";

// Re-export L0 types that other forge modules import from this file
export type { BrickKind, BrickLifecycle, BrickRequires, ForgeScope };

// ---------------------------------------------------------------------------
// Forge result (pure data — L1 handles mutation)
// ---------------------------------------------------------------------------

export interface ForgeResultMetadata {
  readonly forgedAt: number;
  readonly forgedBy: string;
  readonly sessionId: string;
  readonly depth: number;
}

export interface ForgeResult {
  readonly id: BrickId;
  readonly kind: BrickKind;
  readonly name: string;
  readonly descriptor: ToolDescriptor;
  readonly trustTier: TrustTier;
  readonly scope: ForgeScope;
  readonly lifecycle: BrickLifecycle;
  readonly verificationReport: VerificationReport;
  readonly metadata: ForgeResultMetadata;
  /** Number of forge operations consumed. When onForgeConsumed is provided in ForgeDeps, incrementing is automatic; otherwise the caller must increment forgesThisSession by this amount. */
  readonly forgesConsumed: number;
}

// ---------------------------------------------------------------------------
// Verification report
// ---------------------------------------------------------------------------

export type VerificationStage = "static" | "format" | "resolve" | "sandbox" | "self_test" | "trust";

export interface StageReport {
  readonly stage: VerificationStage;
  readonly passed: boolean;
  readonly durationMs: number;
  readonly message?: string;
}

export interface ResolveStageReport extends StageReport {
  readonly stage: "resolve";
  /** Workspace path for bricks with npm dependencies, undefined if no packages. */
  readonly workspacePath?: string;
  /** Entry file path for the brick's implementation, undefined if no packages. */
  readonly entryPath?: string;
}

export interface TrustStageReport extends StageReport {
  readonly stage: "trust";
  readonly trustTier: TrustTier;
}

export interface SelfTestStageReport extends StageReport {
  readonly stage: "self_test";
  readonly testCasesRun: number;
  readonly agentProvidedCount: number;
  readonly autoGeneratedCount: number;
}

export interface VerificationReport {
  readonly stages: readonly StageReport[];
  readonly finalTrustTier: TrustTier;
  readonly totalDurationMs: number;
  readonly passed: boolean;
}

// ---------------------------------------------------------------------------
// Forge inputs (discriminated union)
// ---------------------------------------------------------------------------

export type { TestCase } from "@koi/core";

/** Shared fields present on every forge input variant. */
export interface ForgeInputBase {
  readonly name: string;
  readonly description: string;
  readonly tags?: readonly string[];
  readonly files?: Readonly<Record<string, string>>;
  readonly requires?: BrickRequires;
  readonly classification?: DataClassification;
  readonly contentMarkers?: readonly ContentMarker[];
}

export interface ForgeToolInput extends ForgeInputBase {
  readonly kind: "tool";
  readonly inputSchema: Readonly<Record<string, unknown>>;
  readonly outputSchema?: Readonly<Record<string, unknown>> | undefined;
  readonly implementation: string;
  readonly testCases?: readonly TestCase[];
  readonly configSchema?: Readonly<Record<string, unknown>>;
}

export interface ForgeSkillInput extends ForgeInputBase {
  readonly kind: "skill";
  /** Markdown body of the skill (the raw content, not the generated SKILL.md). */
  readonly body: string;
}

export interface ForgeAgentInputWithManifest extends ForgeInputBase {
  readonly kind: "agent";
  readonly manifestYaml: string;
  readonly brickIds?: undefined;
}

export interface ForgeAgentInputWithBricks extends ForgeInputBase {
  readonly kind: "agent";
  readonly brickIds: readonly string[];
  readonly manifestYaml?: undefined;
  readonly model?: string;
  readonly agentType?: string;
}

export type ForgeAgentInput = ForgeAgentInputWithManifest | ForgeAgentInputWithBricks;

export interface ForgeMiddlewareInput extends ForgeInputBase {
  readonly kind: "middleware";
  readonly implementation: string;
  readonly testCases?: readonly TestCase[];
  readonly configSchema?: Readonly<Record<string, unknown>>;
}

export interface ForgeChannelInput extends ForgeInputBase {
  readonly kind: "channel";
  readonly implementation: string;
  readonly testCases?: readonly TestCase[];
  readonly configSchema?: Readonly<Record<string, unknown>>;
}

export interface ForgeCompositeInput extends ForgeInputBase {
  readonly kind: "composite";
  readonly brickIds: readonly string[];
}

export type ForgeInput =
  | ForgeToolInput
  | ForgeSkillInput
  | ForgeAgentInput
  | ForgeMiddlewareInput
  | ForgeChannelInput
  | ForgeCompositeInput;

// ---------------------------------------------------------------------------
// Pluggable verifier (Stage 3)
// ---------------------------------------------------------------------------

export interface VerifierResult {
  readonly passed: boolean;
  readonly message?: string;
}

export interface ForgeVerifier {
  readonly name: string;
  readonly verify: (input: ForgeInput, context: ForgeContext) => Promise<VerifierResult>;
}

// Sandbox executor — canonical definitions live in @koi/core (L0)
export type {
  SandboxError,
  SandboxErrorCode,
  SandboxExecutor,
  SandboxResult,
  TieredSandboxExecutor,
  TierResolution,
} from "@koi/core";

// ---------------------------------------------------------------------------
// Forge context
// ---------------------------------------------------------------------------

export interface ForgeContext {
  readonly agentId: string;
  readonly depth: number;
  readonly sessionId: string;
  readonly forgesThisSession: number;
  /** Zone identifier for zone-scoped brick visibility. */
  readonly zoneId?: string | undefined;
}

// Brick artifact types — canonical definitions live in @koi/core (L0)
export type {
  AgentArtifact,
  BrickArtifact,
  BrickArtifactBase,
  CompositeArtifact,
  ImplementationArtifact,
  SkillArtifact,
  ToolArtifact,
} from "@koi/core";

// ---------------------------------------------------------------------------
// Promote result (returned by promote_forge)
// ---------------------------------------------------------------------------

export interface PromoteChange<T> {
  readonly from: T;
  readonly to: T;
}

export interface PromoteResult {
  readonly brickId: BrickId;
  readonly applied: boolean;
  readonly requiresHumanApproval: boolean;
  readonly changes: {
    readonly scope?: PromoteChange<ForgeScope>;
    readonly trustTier?: PromoteChange<TrustTier>;
    readonly lifecycle?: PromoteChange<BrickLifecycle>;
  };
  readonly message?: string;
}

// ---------------------------------------------------------------------------
// Manifest parser (injected dependency — avoids L2 peer import of @koi/manifest)
// ---------------------------------------------------------------------------

export type ManifestParseResult =
  | { readonly ok: true; readonly warnings: readonly string[] }
  | { readonly ok: false; readonly error: string };

export interface ManifestParser {
  readonly parse: (yaml: string) => ManifestParseResult | Promise<ManifestParseResult>;
}

// Forge query — canonical definition lives in @koi/core (L0)
export type { ForgeQuery } from "@koi/core";
