/**
 * Generate nexus.yaml and supporting files directly — no external CLI dependency.
 *
 * Replaces the `nexus init` shell-out with a pure TypeScript generator.
 * Each workspace gets a deterministic port derived from its path and
 * a workspace-local data directory for isolation.
 */

import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GenerateNexusConfigOptions {
  /** Koi preset ID (local, demo, mesh). */
  readonly koiPreset: string;
  /** Working directory where files will be written. Default: process.cwd(). */
  readonly cwd?: string | undefined;
  /** Override the HTTP port (skips derivation). */
  readonly port?: number | undefined;
  /** Docker image channel: "stable" or "edge". Default: "edge". */
  readonly channel?: "stable" | "edge" | undefined;
  /** Emit verbose diagnostics to stderr. Default: false. */
  readonly verbose?: boolean | undefined;
}

// ---------------------------------------------------------------------------
// Nexus preset mapping
// ---------------------------------------------------------------------------

/** Maps Koi preset IDs to Nexus preset IDs. */
const PRESET_MAP: Readonly<Record<string, string>> = {
  local: "local",
  demo: "demo",
  mesh: "shared",
  sqlite: "demo",
} as const;

// ---------------------------------------------------------------------------
// Port derivation
// ---------------------------------------------------------------------------

/** Ephemeral port range for derived ports. */
const PORT_RANGE_MIN = 10000;
const PORT_RANGE_MAX = 60000;
const PORT_RANGE_SIZE = PORT_RANGE_MAX - PORT_RANGE_MIN;

/**
 * Derive a stable port number from a workspace path.
 *
 * Uses SHA-256 of the resolved absolute path, takes the first 4 hex chars,
 * and maps to the ephemeral range 10000-60000. Each worktree gets a stable
 * unique port without collisions.
 */
export function derivePort(cwd: string): number {
  const absolute = resolve(cwd);
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(absolute);
  const hex = hasher.digest("hex").slice(0, 8);
  const num = Number.parseInt(hex, 16);
  return PORT_RANGE_MIN + (num % PORT_RANGE_SIZE);
}

// ---------------------------------------------------------------------------
// API key generation
// ---------------------------------------------------------------------------

/** Generate a random API key in sk-* format (Base64URL, 43 chars). */
function generateApiKey(): string {
  const bytes = randomBytes(32);
  const base64url = bytes.toString("base64url");
  return `sk-${base64url}`;
}

// ---------------------------------------------------------------------------
// YAML generation
// ---------------------------------------------------------------------------

/** Default Docker image reference. */
const DEFAULT_IMAGE_REF_STABLE = "ghcr.io/nexi-lab/nexus:stable";
const DEFAULT_IMAGE_REF_EDGE = "ghcr.io/nexi-lab/nexus:edge";

/**
 * Generate the nexus.yaml content string.
 *
 * Matches the format produced by `nexus init --preset <preset>` so that
 * `nexus up` can consume it without modification.
 */
function generateNexusYamlContent(
  nexusPreset: string,
  dataDir: string,
  httpPort: number,
  apiKey: string,
  channel: "stable" | "edge",
  composeFilePath: string,
): string {
  const imageRef = channel === "stable" ? DEFAULT_IMAGE_REF_STABLE : DEFAULT_IMAGE_REF_EDGE;

  return `preset: ${nexusPreset}
data_dir: ${dataDir}
auth: database
tls: false
services:
- nexus
- postgres
- dragonfly
- zoekt
ports:
  http: ${String(httpPort)}
  grpc: ${String(httpPort + 2)}
  postgres: 5432
  dragonfly: 6379
  zoekt: 6070
compose_profiles:
- core
- cache
- search
api_key: ${apiKey}
compose_file: ${composeFilePath}
image_accelerator: cpu
image_ref: ${imageRef}
image_channel: ${channel}
`;
}

// ---------------------------------------------------------------------------
// Docker Compose template
// ---------------------------------------------------------------------------

/** Static Docker Compose file for the Nexus stack. */
const COMPOSE_TEMPLATE = `# Nexus Stack — Portable Compose File
# ====================================
# Generated by koi up. Pulls prebuilt images from GHCR.
# Services are activated via Docker Compose profiles.

services:
  # PostgreSQL Database (with pgvector for semantic search)
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    profiles:
      - core
    environment:
      POSTGRES_DB: \${POSTGRES_DB:-nexus}
      POSTGRES_USER: \${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-nexus}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-wal-archive:/var/lib/postgresql/wal_archive
      - \${NEXUS_PGVECTOR_INIT_SQL:-./001-enable-pgvector.sql}:/docker-entrypoint-initdb.d/001-enable-pgvector.sql:ro
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c effective_io_concurrency=16
      -c maintenance_io_concurrency=16
      -c wal_compression=lz4
      -c shared_buffers=1GB
      -c effective_cache_size=3GB
    ports:
      - "\${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-postgres} -d \${POSTGRES_DB:-nexus}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - nexus-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nexus RPC Server (prebuilt image from GHCR)
  nexus:
    image: \${NEXUS_IMAGE_REF:-ghcr.io/nexi-lab/nexus:latest}
    restart: unless-stopped
    profiles:
      - core
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NEXUS_HOST: "0.0.0.0"
      NEXUS_PORT: "2026"
      NEXUS_AUDIT_STRICT_MODE: "false"
      NEXUS_DATA_DIR: /app/data
      NEXUS_DATABASE_URL: postgresql://\${POSTGRES_USER:-postgres}:\${POSTGRES_PASSWORD:-nexus}@postgres:5432/\${POSTGRES_DB:-nexus}
      NEXUS_ADMIN_USER: \${NEXUS_ADMIN_USER:-admin}
      NEXUS_AUTH_TYPE: \${NEXUS_AUTH_TYPE:-database}
      NEXUS_API_KEY: \${NEXUS_API_KEY:-}
      NEXUS_SEARCH_DAEMON: "true"
      NEXUS_SKIP_PERMISSIONS: \${NEXUS_SKIP_PERMISSIONS:-false}
      NEXUS_ENFORCE_PERMISSIONS: \${NEXUS_ENFORCE_PERMISSIONS:-true}
      NEXUS_ALLOW_ADMIN_BYPASS: \${NEXUS_ALLOW_ADMIN_BYPASS:-true}
      NEXUS_DRAGONFLY_URL: \${NEXUS_DRAGONFLY_URL:-redis://dragonfly:6379}
      NEXUS_CACHE_EMBEDDING_TTL: \${NEXUS_CACHE_EMBEDDING_TTL:-86400}
      NEXUS_GRPC_PORT: "\${NEXUS_GRPC_PORT:-2028}"
      ZOEKT_ENABLED: "false"
      ZOEKT_URL: \${ZOEKT_URL:-http://zoekt:6070}
    volumes:
      - \${NEXUS_HOST_DATA_DIR:-./nexus-data}:/app/data
    ports:
      - "\${NEXUS_PORT:-2026}:2026"
      - "\${NEXUS_GRPC_PORT:-2028}:\${NEXUS_GRPC_PORT:-2028}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2026/health"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    networks:
      - nexus-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # DragonflyDB — Hot Cache
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: unless-stopped
    profiles:
      - cache
    command: >
      --cache_mode=true
      --maxmemory=512mb
      --proactor_threads=2
    ports:
      - "\${DRAGONFLY_PORT:-6379}:6379"
    volumes:
      - dragonfly-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - nexus-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Zoekt — Fast Code Search
  zoekt:
    image: \${ZOEKT_IMAGE_REF:-ghcr.io/nexi-lab/nexus-zoekt:stable}
    restart: unless-stopped
    profiles:
      - search
    command: ["-index", "/index", "-listen", ":6070"]
    environment:
      ZOEKT_INDEX_DIR: /index
      ZOEKT_DATA_DIR: /data
    volumes:
      - \${NEXUS_HOST_DATA_DIR:-./nexus-data}:/data
      - zoekt-index:/index
    ports:
      - "\${ZOEKT_PORT:-6070}:6070"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:6070/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nexus-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # NATS JetStream — Durable Event Bus (optional add-on)
  nats:
    image: nats:2.10-alpine
    restart: unless-stopped
    profiles:
      - events
    command: ["--jetstream", "--store_dir=/data", "-m", "8222"]
    ports:
      - "\${NATS_PORT:-4222}:4222"
      - "\${NATS_MONITOR_PORT:-8222}:8222"
    volumes:
      - nats-data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q --spider http://localhost:8222/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - nexus-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-data:
    driver: local
  postgres-wal-archive:
    driver: local
  dragonfly-data:
    driver: local
  zoekt-index:
    driver: local
  nats-data:
    driver: local

networks:
  nexus-network:
    driver: bridge
`;

/** pgvector init SQL — required by PostgreSQL Docker entrypoint. */
const PGVECTOR_INIT_SQL = `-- Enable pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;
`;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate nexus.yaml and supporting files directly in the workspace.
 *
 * Creates:
 * - `nexus.yaml` — Nexus configuration with workspace-local data_dir and derived port
 * - `nexus-stack.yml` — Docker Compose file for the Nexus stack
 * - `001-enable-pgvector.sql` — PostgreSQL init script for pgvector
 *
 * Does NOT overwrite existing files (check before calling).
 */
export function generateNexusConfig(options: GenerateNexusConfigOptions): void {
  const cwd = options.cwd ?? process.cwd();
  const verbose = options.verbose ?? false;
  const channel = options.channel ?? "edge";
  const nexusPreset = PRESET_MAP[options.koiPreset] ?? "demo";

  const httpPort = options.port ?? derivePort(cwd);
  const dataDir = join(resolve(cwd), "nexus-data");
  const apiKey = generateApiKey();
  const composeFilePath = join(resolve(cwd), "nexus-stack.yml");

  // Ensure data directory exists
  if (!existsSync(dataDir)) {
    mkdirSync(dataDir, { recursive: true });
  }

  // Write nexus.yaml
  const yamlPath = join(cwd, "nexus.yaml");
  const yamlContent = generateNexusYamlContent(
    nexusPreset,
    dataDir,
    httpPort,
    apiKey,
    channel,
    composeFilePath,
  );
  writeFileSync(yamlPath, yamlContent, "utf-8");
  if (verbose) {
    process.stderr.write(`Nexus: generated ${yamlPath} (port=${String(httpPort)})\n`);
  }

  // Write nexus-stack.yml (Docker Compose)
  const composePath = join(cwd, "nexus-stack.yml");
  if (!existsSync(composePath)) {
    writeFileSync(composePath, COMPOSE_TEMPLATE, "utf-8");
    if (verbose) {
      process.stderr.write(`Nexus: generated ${composePath}\n`);
    }
  }

  // Write pgvector init SQL
  const sqlPath = join(cwd, "001-enable-pgvector.sql");
  if (!existsSync(sqlPath)) {
    writeFileSync(sqlPath, PGVECTOR_INIT_SQL, "utf-8");
    if (verbose) {
      process.stderr.write(`Nexus: generated ${sqlPath}\n`);
    }
  }
}
