/**
 * Nexus CLI lifecycle management — delegates to `nexus init/up/down`.
 *
 * Replaces manual process spawning + PID tracking with Nexus's own
 * Docker Compose-based lifecycle (nexi-lab/nexus#2918).
 *
 * Only for Docker-backed presets (demo, shared). The `local` preset
 * exits immediately from `nexus up` without starting services — use
 * the legacy `ensureNexusRunning()` path for local/embed-lite mode.
 *
 * - `nexusInit()` scaffolds `nexus.yaml` via `nexus init --preset <preset>`
 * - `nexusUp()` starts the Nexus stack via `nexus up` (blocks until healthy)
 * - `nexusStop()` pauses the stack via `nexus stop` (fast, keeps containers)
 * - `nexusDown()` destroys the stack via `nexus down` (removes containers)
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { KoiError, Result } from "@koi/core";
import { checkBinaryAvailable, resolveNexusBinary } from "./binary-resolver.js";
import { DEFAULT_HOST, DEFAULT_PORT, STATE_JSON_FILE } from "./constants.js";
import { generateNexusConfig } from "./generate-nexus-config.js";
import type { NexusRuntimeState } from "./types.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Options shared by all lifecycle commands. */
export interface NexusLifecycleOptions {
  /** Working directory where nexus.yaml lives. Default: process.cwd(). */
  readonly cwd?: string | undefined;
  /** Emit verbose diagnostics to stderr. Default: false. */
  readonly verbose?: boolean | undefined;
  /** Nexus source directory for `uv run --directory <sourceDir> nexus`. */
  readonly sourceDir?: string | undefined;
}

/** Extended options for `nexusInit()`. */
export interface NexusInitOptions extends NexusLifecycleOptions {
  /** Override the HTTP port in nexus.yaml (patched after scaffolding). */
  readonly port?: number | undefined;
  /** Docker image channel: "stable" or "edge". Default: "edge". */
  readonly channel?: "stable" | "edge" | undefined;
}

/** Result of a successful `nexus up`. */
export interface NexusUpResult {
  /** Base URL of the running Nexus API (read from nexus.yaml after startup). */
  readonly baseUrl: string;
  /** Admin API key from nexus.yaml (generated by `nexus init` for auth-enabled presets). */
  readonly apiKey: string | undefined;
  /** Whether `nexus init` was auto-run because nexus.yaml was missing. */
  readonly autoInitialized: boolean;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Scaffolds `nexus.yaml` and supporting files for the Nexus Docker stack.
 *
 * Generates config directly in TypeScript — no external `nexus` CLI dependency.
 * Each workspace gets a deterministic port derived from its path and a
 * workspace-local `nexus-data/` directory for isolation.
 *
 * Maps Koi preset IDs to Nexus preset IDs:
 * - local → local, demo → demo, mesh → shared
 */
export async function nexusInit(
  koiPreset: string,
  options?: NexusInitOptions | undefined,
): Promise<Result<void, KoiError>> {
  const cwd = options?.cwd ?? process.cwd();
  const verbose = options?.verbose ?? false;

  try {
    generateNexusConfig({
      koiPreset,
      cwd,
      port: options?.port,
      channel: options?.channel,
      verbose,
    });
    return { ok: true, value: undefined };
  } catch (err: unknown) {
    return {
      ok: false,
      error: {
        code: "EXTERNAL" as const,
        message: `Failed to generate nexus.yaml: ${err instanceof Error ? err.message : String(err)}`,
        retryable: false,
        context: { cwd },
      },
    };
  }
}

/**
 * Starts the Nexus Docker Compose stack via `nexus up`.
 *
 * **Important**: Only call this for Docker-backed presets (demo, mesh/shared).
 * The `local` preset's `nexus up` exits with code 0 without starting services.
 * For local/embed-lite mode, use `ensureNexusRunning()` instead.
 *
 * If `nexus.yaml` doesn't exist in the working directory, auto-runs
 * `nexus init --preset <koiPreset>` first.
 *
 * After startup, reads `nexus.yaml` to extract the actual HTTP port
 * (which may differ from the default if ports were auto-shifted during
 * conflict resolution).
 */
export async function nexusUp(
  options?: NexusLifecycleOptions & {
    /** Koi preset for auto-init when nexus.yaml is missing. Default: "demo". */
    readonly koiPreset?: string | undefined;
    /** Host override. Default: "127.0.0.1". */
    readonly host?: string | undefined;
    /** Build images from source (passes --build and --compose-file to `nexus up`). Requires `sourceDir` pointing to the nexus repo root. */
    readonly build?: boolean | undefined;
    /** Path to the nexus repo root for --build (derives compose file as `<sourceDir>/docker-compose.yml`). */
    readonly sourceDir?: string | undefined;
    /** Port conflict resolution strategy (passes --port-strategy to `nexus up`). Default: "auto". */
    readonly portStrategy?: "auto" | "prompt" | "fail" | undefined;
    /** Override the HTTP port (passed to `nexus init` during auto-init). */
    readonly port?: number | undefined;
    /** Docker image channel for auto-init: "stable" or "edge". Default: "edge". */
    readonly channel?: "stable" | "edge" | undefined;
  },
): Promise<Result<NexusUpResult, KoiError>> {
  const cwd = options?.cwd ?? process.cwd();
  const verbose = options?.verbose ?? false;
  const host = options?.host ?? DEFAULT_HOST;
  const sourceDir = options?.sourceDir;

  const binaryCheck = await ensureBinary(sourceDir);
  if (!binaryCheck.ok) {
    // Fallback: if nexus CLI is unavailable but nexus.yaml + compose_file exist,
    // run docker compose directly. This handles environments where `uv` or `nexus`
    // isn't installed but Docker is available and the stack was previously initialized.
    const fallbackResult = await dockerComposeFallback(cwd, verbose, host);
    if (fallbackResult !== undefined) return fallbackResult;
    return binaryCheck;
  }

  // Auto-init if no config file exists (nexus.yaml or nexus.yml)
  let autoInitialized = false;
  let configPath = findNexusConfig(cwd);
  if (configPath === undefined) {
    const koiPreset = options?.koiPreset ?? "demo";
    if (verbose) {
      process.stderr.write(
        `Nexus: nexus.yaml not found, running nexus init --preset ${koiPreset}\n`,
      );
    }
    const initResult = await nexusInit(koiPreset, {
      cwd,
      verbose,
      sourceDir,
      port: options?.port,
      channel: options?.channel,
    });
    if (!initResult.ok) return initResult;
    autoInitialized = true;
    configPath = findNexusConfig(cwd) ?? join(cwd, "nexus.yaml");
  }

  // Always validate data_dir points to ${cwd}/nexus-data — even when nexus.yaml
  // pre-exists. A stale nexus.yaml (e.g., copied from another worktree or symlinked
  // from ~/.koi/demo/) may point to a different worktree's data dir, causing
  // cross-worktree contamination and Nexus write failures.
  patchNexusDataDir(cwd, verbose);

  // Clear NEXUS_API_KEY from the environment before starting Docker.
  // The nexus.yaml api_key uses nx_admin_* format which the database auth
  // provider rejects (requires sk-* prefix). By clearing it, the container
  // entrypoint auto-generates a proper sk-* admin key.
  const savedApiKey = process.env.NEXUS_API_KEY;
  delete process.env.NEXUS_API_KEY;

  // Fast resume: if .state.json exists from a previous run, use `nexus start`
  // instead of `nexus up`. `nexus start` resumes paused containers without
  // pulling images or re-resolving ports — much faster for repeat startups.
  // Only fall through to `nexus up` for first-run or when --build is requested.
  const existingState = readRuntimeState(cwd);
  const canFastResume = existingState !== undefined && options?.build !== true && !autoInitialized;

  let upResult: Result<void, KoiError>;
  if (canFastResume) {
    if (verbose) {
      process.stderr.write(
        `Nexus: reusing existing instance at http://${host}:${String(existingState.ports.http)}\n`,
      );
    }
    upResult = await runNexusCommand(["start"], cwd, verbose, "nexus start", sourceDir);
    // If start fails (e.g. containers were killed/removed), clean up stale
    // containers before full restart. Without this, `nexus up` sees the old
    // containers occupying the port and allocates a new one (#1077).
    if (!upResult.ok) {
      if (verbose) {
        process.stderr.write("Nexus: fast resume failed, cleaning up stale containers\n");
      }
      // Remove dead containers so the configured port is freed.
      // Result intentionally ignored — if down fails (already removed), up still works.
      await runNexusCommand(["down"], cwd, verbose, "nexus down", sourceDir);
      upResult = await runNexusFullUp(options, cwd, verbose, sourceDir);
    }
  } else {
    upResult = await runNexusFullUp(options, cwd, verbose, sourceDir);
  }

  // Restore the original env var (may be needed by other code)
  if (savedApiKey !== undefined) {
    process.env.NEXUS_API_KEY = savedApiKey;
  }
  if (!upResult.ok) return upResult;

  // Read connection info from .state.json (authoritative source written by
  // `nexus up` after health checks pass). Falls back to nexus.yaml if
  // .state.json is missing (e.g., first run before health check completes).
  const runtimeState = readRuntimeState(cwd);
  const yamlConfig = readNexusConfig(configPath);

  const port = runtimeState?.ports.http ?? yamlConfig.port;
  const baseUrl = `http://${host}:${String(port)}`;

  // .state.json api_key is the sk-* key written by the container entrypoint.
  // Fall back to nexus.yaml api_key (nx_admin_* format) only if .state.json
  // doesn't have one — callers should prefer the sk-* key for database auth.
  const apiKey = runtimeState?.api_key || yamlConfig.apiKey;

  // Write to shared location so other worktrees can discover the key
  if (apiKey !== undefined) {
    const { writeSharedNexusKey } = await import("./ensure-running.js");
    writeSharedNexusKey(apiKey);
  }

  return { ok: true, value: { baseUrl, apiKey, autoInitialized } };
}

/**
 * Pauses the Nexus stack via `nexus stop` (keeps containers and volumes).
 *
 * Containers are stopped but not removed. Resume with `nexus start` or
 * `nexus up` (which detects stopped containers and does a fast resume).
 * This is much faster than `nexusDown()` + `nexusUp()` because it skips
 * port resolution, image pulls, and full health checks.
 */
export async function nexusStop(options?: NexusLifecycleOptions): Promise<Result<void, KoiError>> {
  const cwd = options?.cwd ?? process.cwd();
  const verbose = options?.verbose ?? false;
  const sourceDir = options?.sourceDir;

  const binaryCheck = await ensureBinary(sourceDir);
  if (!binaryCheck.ok) return binaryCheck;

  return runNexusCommand(["stop"], cwd, verbose, "nexus stop", sourceDir);
}

/**
 * Destroys the Nexus stack via `nexus down` (removes containers).
 *
 * For normal shutdown, prefer `nexusStop()` which keeps containers for
 * fast resume. Use `nexusDown()` only for full cleanup or when volumes
 * need to be removed.
 */
export async function nexusDown(
  options?: NexusLifecycleOptions & {
    /** Also remove volumes (passes --volumes to `nexus down`). Default: false. */
    readonly volumes?: boolean | undefined;
  },
): Promise<Result<void, KoiError>> {
  const cwd = options?.cwd ?? process.cwd();
  const verbose = options?.verbose ?? false;
  const sourceDir = options?.sourceDir;

  const binaryCheck = await ensureBinary(sourceDir);
  if (!binaryCheck.ok) return binaryCheck;

  const args: string[] = ["down"];
  if (options?.volumes === true) args.push("--volumes");

  return runNexusCommand(args, cwd, verbose, "nexus down", sourceDir);
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

/**
 * Fallback: start Nexus via `docker compose` directly when the `nexus` CLI
 * isn't available. Reads compose_file + data_dir + ports from nexus.yaml.
 * Returns undefined if fallback isn't possible (no nexus.yaml, no compose_file).
 */
async function dockerComposeFallback(
  cwd: string,
  verbose: boolean,
  host: string,
): Promise<Result<NexusUpResult, KoiError> | undefined> {
  const configPath = findNexusConfig(cwd);
  if (configPath === undefined) return undefined;

  try {
    const raw = readFileSync(configPath, "utf-8");
    const composeMatch = /^compose_file:\s*['"]?(.+?)['"]?\s*$/m.exec(raw);
    if (composeMatch?.[1] === undefined || !existsSync(composeMatch[1])) return undefined;
    const composeFile = composeMatch[1];

    // Read data_dir for volume mount
    const dataDirMatch = /^data_dir:\s*['"]?(.+?)['"]?\s*$/m.exec(raw);
    const dataDir = dataDirMatch?.[1] ?? join(cwd, "nexus-data");

    // Read profiles
    const profiles: string[] = [];
    const profileSection = /^compose_profiles:\s*\n((?:\s*-\s*.+\n)*)/m.exec(raw);
    if (profileSection?.[1] !== undefined) {
      for (const m of profileSection[1].matchAll(/^\s*-\s*(.+)/gm)) {
        if (m[1] !== undefined) profiles.push(m[1].trim());
      }
    }

    // Read port + api_key
    const config = readNexusConfig(configPath);

    if (verbose) {
      process.stderr.write(
        `Nexus: nexus CLI unavailable, falling back to docker compose\n` +
          `  compose_file: ${composeFile}\n` +
          `  data_dir: ${dataDir}\n`,
      );
    }

    // Build docker compose command with a unique project name derived from
    // the data_dir hash. This prevents conflicts when multiple worktrees
    // use the same compose_file but different data directories.
    const projectHash = createHash("md5").update(dataDir).digest("hex").slice(0, 8);
    const projectName = `nexus-${projectHash}`;
    const args = ["compose", "-f", composeFile, "-p", projectName];
    for (const p of profiles) {
      args.push("--profile", p);
    }
    args.push("up", "-d", "--wait");

    const proc = Bun.spawn(["docker", ...args], {
      cwd,
      stdin: "ignore",
      stdout: "pipe",
      stderr: "pipe",
      env: {
        ...process.env,
        NEXUS_HOST_DATA_DIR: dataDir,
        NEXUS_PORT: String(config.port),
        NEXUS_GRPC_PORT: String(config.port + 1),
        POSTGRES_PORT: String(config.port + 2),
        DRAGONFLY_PORT: String(config.port + 3),
        ZOEKT_PORT: String(config.port + 4),
        DOCKER_CLI_HINTS: "false",
        BUILDKIT_PROGRESS: "plain",
      },
    });

    const exitCode = await proc.exited;
    if (exitCode !== 0) {
      const stderr = await new Response(proc.stderr).text();
      return {
        ok: false,
        error: {
          code: "INTERNAL" as const,
          message: `docker compose up failed (exit ${String(exitCode)}): ${stderr.slice(0, 500)}`,
          retryable: false,
          context: {},
        },
      };
    }

    const baseUrl = `http://${host}:${String(config.port)}`;
    return {
      ok: true,
      value: { baseUrl, apiKey: config.apiKey, autoInitialized: false },
    };
  } catch {
    return undefined;
  }
}

/** Run full `nexus up` with all flags (pull, build, port-strategy). */
async function runNexusFullUp(
  options: Parameters<typeof nexusUp>[0],
  cwd: string,
  verbose: boolean,
  sourceDir: string | undefined,
): Promise<Result<void, KoiError>> {
  const upArgs: string[] = ["up"];
  if (options?.sourceDir !== undefined) {
    upArgs.push("--compose-file", join(options.sourceDir, "docker-compose.yml"));
  }
  if (options?.build === true) upArgs.push("--build");
  if (options?.portStrategy !== undefined) upArgs.push("--port-strategy", options.portStrategy);
  return runNexusCommand(upArgs, cwd, verbose, "nexus up", sourceDir);
}

/** Checks that the nexus binary is available on PATH. */
async function ensureBinary(sourceDir?: string | undefined): Promise<Result<void, KoiError>> {
  const binaryParts = resolveNexusBinary(sourceDir);
  const available = await checkBinaryAvailable(binaryParts);
  if (!available) {
    const binaryName = binaryParts[0] ?? "nexus";
    return {
      ok: false,
      error: {
        code: "NOT_FOUND" as const,
        message: `Cannot find '${binaryName}' on PATH. Install it:\n  - uv: pip install nexus-ai-fs\n  - Or set NEXUS_COMMAND`,
        retryable: false,
        context: { binary: binaryName },
      },
    };
  }
  return { ok: true, value: undefined };
}

/** Nexus config search paths (nexus.yaml preferred, nexus.yml fallback). */
const CONFIG_NAMES = ["nexus.yaml", "nexus.yml"] as const;

/**
 * Finds the nexus config file in the given directory.
 * Searches for nexus.yaml first, then nexus.yml.
 */
function findNexusConfig(cwd: string): string | undefined {
  for (const name of CONFIG_NAMES) {
    const candidate = join(cwd, name);
    if (existsSync(candidate)) return candidate;
  }
  return undefined;
}

/**
 * Reads the Nexus runtime state from `{data_dir}/.state.json`.
 *
 * `.state.json` is written by `nexus up` after health checks complete and
 * contains the authoritative resolved ports, API key, and project name.
 * The `data_dir` is read from `nexus.yaml` (stored as an absolute path).
 *
 * Returns `undefined` if `nexus.yaml` or `.state.json` is missing/unreadable.
 */
export function readRuntimeState(cwd: string): NexusRuntimeState | undefined {
  const configPath = findNexusConfig(cwd);
  if (configPath === undefined) return undefined;

  try {
    const raw = readFileSync(configPath, "utf-8");
    // Extract data_dir (absolute path set by `nexus init`)
    const dataDirMatch = /^data_dir:\s*['"]?(.+?)['"]?\s*$/m.exec(raw);
    if (dataDirMatch?.[1] === undefined) return undefined;

    const dataDir = dataDirMatch[1];
    const statePath = join(dataDir, STATE_JSON_FILE);
    if (!existsSync(statePath)) return undefined;

    const stateRaw = readFileSync(statePath, "utf-8");
    const parsed: unknown = JSON.parse(stateRaw);
    if (typeof parsed !== "object" || parsed === null) return undefined;

    const state = parsed as Record<string, unknown>;
    // Minimal validation: must have ports object
    if (typeof state.ports !== "object" || state.ports === null) return undefined;

    return parsed as NexusRuntimeState;
  } catch {
    return undefined;
  }
}

/** Values extracted from nexus.yaml after startup. */
interface NexusConfigValues {
  readonly port: number;
  readonly apiKey: string | undefined;
}

/**
 * Reads key values from nexus.yaml: HTTP port and API key.
 *
 * Uses simple regex extraction to avoid a YAML parser dependency.
 * nexus.yaml is materialized with explicit keys by `nexus init`,
 * so these regexes are safe.
 */
function readNexusConfig(configPath: string): NexusConfigValues {
  try {
    const raw = readFileSync(configPath, "utf-8");

    // Extract ports.http
    let port = DEFAULT_PORT;
    const portsSection = /^ports:\s*\n((?:\s+\S.*\n)*)/m.exec(raw);
    if (portsSection !== undefined && portsSection !== null) {
      const httpMatch = /^\s+http:\s*(\d+)/m.exec(portsSection[1] ?? "");
      if (httpMatch?.[1] !== undefined) {
        const parsed = Number.parseInt(httpMatch[1], 10);
        if (!Number.isNaN(parsed) && parsed > 0) port = parsed;
      }
    }

    // Extract api_key (top-level key, format: api_key: nx_admin_...)
    let apiKey: string | undefined;
    const apiKeyMatch = /^api_key:\s*['"]?(\S+?)['"]?\s*$/m.exec(raw);
    if (apiKeyMatch?.[1] !== undefined && apiKeyMatch[1].length > 0) {
      apiKey = apiKeyMatch[1];
    }

    return { port, apiKey };
  } catch {
    // File missing or unreadable — use defaults
    return { port: DEFAULT_PORT, apiKey: undefined };
  }
}

/**
 * Runs a nexus CLI subcommand and waits for it to exit.
 *
 * Always captures both stdout and stderr so that Nexus CLI errors
 * (emitted via Rich Console to stdout) are surfaced in error messages.
 * In verbose mode, output is also forwarded to inherit streams.
 */
async function runNexusCommand(
  args: readonly string[],
  cwd: string,
  verbose: boolean,
  label: string,
  sourceDir?: string | undefined,
): Promise<Result<void, KoiError>> {
  const binaryParts = resolveNexusBinary(sourceDir);
  const cmd = [...binaryParts, ...args];

  if (verbose) {
    process.stderr.write(`Nexus: running ${cmd.join(" ")}\n`);
  }

  // Read data_dir from nexus.yaml so Docker Compose mounts the correct volume.
  // The compose file uses ${NEXUS_HOST_DATA_DIR:-./nexus-data} for the data mount.
  const dataDirEnv: Record<string, string> = {};
  const configPath = findNexusConfig(cwd);
  if (configPath !== undefined) {
    try {
      const raw = readFileSync(configPath, "utf-8");
      const match = /^data_dir:\s*['"]?(.+?)['"]?\s*$/m.exec(raw);
      if (match?.[1] !== undefined) {
        dataDirEnv.NEXUS_HOST_DATA_DIR = match[1];
      }
    } catch {
      // Non-fatal — compose will use default ./nexus-data
    }
  }

  try {
    const proc = Bun.spawn(cmd, {
      cwd,
      stdin: "ignore",
      // Always pipe to capture output; forward to user in verbose mode after
      stdout: "pipe",
      stderr: "pipe",
      env: {
        ...process.env,
        ...dataDirEnv,
        // Suppress Docker Compose TTY progress bars that bypass pipe redirections
        DOCKER_CLI_HINTS: "false",
        BUILDKIT_PROGRESS: "plain",
        // Prevent Python Rich Console from writing ANSI to /dev/tty
        NO_COLOR: "1",
        TERM: "dumb",
      },
    });

    const exitCode = await proc.exited;

    // Collect output (Nexus CLI uses Rich Console on stdout for most messages)
    const stdoutText = proc.stdout !== null ? await new Response(proc.stdout).text() : "";
    const stderrText = proc.stderr !== null ? await new Response(proc.stderr).text() : "";

    // Forward output in verbose mode
    if (verbose) {
      if (stdoutText) process.stdout.write(stdoutText);
      if (stderrText) process.stderr.write(stderrText);
    }

    if (exitCode !== 0) {
      // Combine stdout + stderr for the error message since Nexus
      // prints most diagnostics to stdout via Rich Console
      const output = [stdoutText.trim(), stderrText.trim()].filter((s) => s.length > 0).join("\n");
      return {
        ok: false,
        error: {
          code: "EXTERNAL" as const,
          message: `${label} exited with code ${String(exitCode)}${output ? `:\n${output}` : ""}`,
          retryable: false,
          context: { cmd, exitCode },
        },
      };
    }

    return { ok: true, value: undefined };
  } catch (err: unknown) {
    return {
      ok: false,
      error: {
        code: "EXTERNAL" as const,
        message: `Failed to run ${label}: ${err instanceof Error ? err.message : String(err)}`,
        retryable: false,
        cause: err,
        context: { cmd },
      },
    };
  }
}
