import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/agent-definition.ts",
    "src/agent-resolver.ts",
    "src/bash-rule-pattern.ts",
    "src/assembly.ts",
    "src/config.ts",
    "src/channel.ts",
    "src/common.ts",
    "src/context.ts",
    "src/delegation.ts",
    "src/daemon.ts",
    "src/ecs.ts",
    "src/handoff.ts",
    "src/engine.ts",
    "src/event-backend.ts",
    "src/errors.ts",
    "src/governance.ts",
    "src/governance-backend.ts",
    "src/hook.ts",
    "src/eviction.ts",
    "src/health.ts",
    "src/hook.ts",
    "src/lifecycle.ts",
    "src/message.ts",
    "src/middleware.ts",
    "src/model-adapter.ts",
    "src/model-provider.ts",
    "src/resolver.ts",
    "src/rich-trajectory.ts",
    "src/retry-signal.ts",
    "src/brick-snapshot.ts",
    "src/brick-store.ts",
    "src/filesystem-backend.ts",
    "src/sandbox-adapter.ts",
    "src/sandbox-executor.ts",
    "src/permission-backend.ts",
    "src/sandbox-profile.ts",
    "src/skill-registry.ts",
    "src/version-index.ts",
    "src/version-types.ts",
    "src/run-report.ts",
    "src/elicitation.ts",
    "src/mailbox.ts",
    "src/webhook.ts",
    "src/intent-capsule.ts",
    "src/security-analyzer.ts",
    "src/pay-ledger.ts",
    "src/procfs.ts",
    "src/process-descriptor.ts",
    "src/scratchpad.ts",
    "src/debug.ts",
    "src/zone.ts",
    "src/cost-tracker.ts",
    "src/user-model.ts",
    "src/replacement.ts",
    "src/memory.ts",
    "src/worker-protocol.ts",
  ],
  format: ["esm"],
  dts: {
    compilerOptions: {
      composite: false,
    },
  },
  // Pre-push runs build and typecheck in parallel; both can trigger core build.
  // Disabling clean avoids dist unlink races between concurrent tsup processes.
  clean: false,
  treeshake: true,
  target: "node22",
});
