/**
 * Vercel adapter types — DESIGN-ONLY in v1.
 *
 * Per spec PR 5: this package is NOT wired into `@koi/runtime` and gets no
 * `koi.edge.vercel` accessor. Operators who opt in import this package
 * directly. Promotion to published-runtime-integrated requires either a
 * provider-owned cleanup primitive OR mechanically-verifiable isolation.
 */

import type { EdgeIntegrityVerification } from "@koi/core";

/** Configuration accepted by `createVercelAdapter`. */
export interface VercelAdapterConfig {
  /** Vercel KV (Upstash Redis-compatible) REST URL. */
  readonly dedupeKvUrl: string;
  /** Vercel KV REST token (full-namespace, NOT the per-pair nonce-burn token). */
  readonly dedupeKvToken: string;
  /** Fleet-namespacing prefix. Same rules as Cloudflare: non-empty, not "default". */
  readonly ownerId: string;
  /** Per-pair Ed25519 keypair material — generated by the host at create() time. */
  readonly pairSigningKeyPem?: string;
  readonly pairVerifyKeyPem?: string;
  /** Same three-mode integrity verification as Cloudflare. */
  readonly integrityVerification?: EdgeIntegrityVerification;
}
