/**
 * Core types for the @koi/forge self-extension system.
 *
 * Re-exported from @koi/forge-types — canonical source is now the L0u package.
 */

export type {
  AgentArtifact,
  BrickArtifact,
  BrickArtifactBase,
  BrickKind,
  BrickLifecycle,
  BrickRequires,
  CompositeArtifact,
  DriftChecker,
  DriftCheckResult,
  ForgeAgentInput,
  ForgeAgentInputWithBricks,
  ForgeAgentInputWithManifest,
  ForgeChannelInput,
  ForgeCompositeInput,
  ForgeContext,
  ForgeInput,
  ForgeInputBase,
  ForgeMiddlewareInput,
  ForgeQuery,
  ForgeResult,
  ForgeResultMetadata,
  ForgeScope,
  ForgeSkillInput,
  ForgeToolInput,
  ForgeVerifier,
  GovernanceResult,
  ImplementationArtifact,
  ManifestParseResult,
  ManifestParser,
  PromoteChange,
  PromoteResult,
  ResolveStageReport,
  SandboxError,
  SandboxErrorCode,
  SandboxExecutor,
  SandboxResult,
  SelfTestStageReport,
  SkillArtifact,
  StageReport,
  TestCase,
  ToolArtifact,
  TrustStageReport,
  VerificationReport,
  VerificationStage,
  VerifierResult,
} from "@koi/forge-types";
