/**
 * Mailbox types — agent-to-agent messaging envelope and ECS component.
 *
 * Provides the L0 contract for inter-agent communication:
 * - `AgentMessage` — the Koi-native message envelope
 * - `MailboxComponent` — the ECS singleton for send/receive/list
 * - `MessageFilter` — declarative inbox filtering
 *
 * L2 adapters (e.g., @koi/ipc-nexus) provide concrete implementations.
 */

import type { JsonObject } from "./common.js";
import type { AgentId } from "./ecs.js";
import type { KoiError, Result } from "./errors.js";

// ---------------------------------------------------------------------------
// Branded MessageId
// ---------------------------------------------------------------------------

declare const __messageBrand: unique symbol;

/** Branded string type for message identifiers. */
export type MessageId = string & { readonly [__messageBrand]: "MessageId" };

/** Create a branded MessageId from a plain string. */
export function messageId(raw: string): MessageId {
  return raw as MessageId;
}

// ---------------------------------------------------------------------------
// Message kind (protocol-level discrimination)
// ---------------------------------------------------------------------------

/** Protocol-level message kind for dispatch and correlation. */
export type MessageKind = "request" | "response" | "event" | "cancel";

// ---------------------------------------------------------------------------
// Agent message envelope
// ---------------------------------------------------------------------------

/** The Koi-native agent-to-agent message envelope. */
export interface AgentMessage {
  readonly id: MessageId;
  readonly from: AgentId;
  readonly to: AgentId;
  readonly kind: MessageKind;
  /** Correlates responses/cancels to the originating request. */
  readonly correlationId?: MessageId | undefined;
  /** ISO-8601 creation timestamp. */
  readonly createdAt: string;
  /** Time-to-live in seconds. Backend may discard expired messages. */
  readonly ttlSeconds?: number | undefined;
  /** Application-level message type (e.g., "code-review", "deploy"). */
  readonly type: string;
  /** Arbitrary structured payload. */
  readonly payload: JsonObject;
  /** Optional metadata (tracing, routing hints, etc.). */
  readonly metadata?: JsonObject | undefined;
}

// ---------------------------------------------------------------------------
// Message input (id + createdAt generated by backend)
// ---------------------------------------------------------------------------

/** Input for send() — `id` and `createdAt` are generated by the backend. */
export type AgentMessageInput = Omit<AgentMessage, "id" | "createdAt">;

// ---------------------------------------------------------------------------
// Message filter
// ---------------------------------------------------------------------------

/** Declarative filter for listing inbox messages. */
export interface MessageFilter {
  readonly kind?: MessageKind | undefined;
  readonly type?: string | undefined;
  readonly from?: AgentId | undefined;
  readonly limit?: number | undefined;
}

// ---------------------------------------------------------------------------
// Mailbox component (ECS singleton)
// ---------------------------------------------------------------------------

/**
 * ECS singleton component for agent-to-agent messaging.
 *
 * - `send` — dispatch a message to another agent's mailbox
 * - `onMessage` — subscribe to incoming messages (returns unsubscribe fn)
 * - `list` — query inbox with optional filter
 */
export interface MailboxComponent {
  readonly send: (message: AgentMessageInput) => Promise<Result<AgentMessage, KoiError>>;
  readonly onMessage: (handler: (message: AgentMessage) => void | Promise<void>) => () => void;
  readonly list: (
    filter?: MessageFilter,
  ) => readonly AgentMessage[] | Promise<readonly AgentMessage[]>;
}
