/**
 * Core types for the @koi/forge self-extension system.
 *
 * Canonical home for forge input/output/verification types.
 * Imported by all @koi/forge-* sub-packages.
 */

import type {
  BrickArtifact,
  BrickId,
  BrickKind,
  BrickLifecycle,
  BrickRequires,
  ContentMarker,
  DataClassification,
  EngineAdapter,
  EvolutionKind,
  ExternalAgentDescriptor,
  ForgeScope,
  ForgeStore,
  GovernanceController,
  KoiError,
  Result,
  SandboxExecutor,
  SigningBackend,
  StoreChangeNotifier,
  TestCase,
  ToolDescriptor,
  ToolOrigin,
  ToolPolicy,
} from "@koi/core";
import type { Retriever } from "@koi/search-provider";

// Re-export L0 types that other forge modules import from this file
export type { BrickKind, BrickLifecycle, BrickRequires, ForgeScope };

// ---------------------------------------------------------------------------
// Forge result (pure data — L1 handles mutation)
// ---------------------------------------------------------------------------

export interface ForgeResultMetadata {
  readonly forgedAt: number;
  readonly forgedBy: string;
  readonly sessionId: string;
  readonly depth: number;
}

export interface ForgeResult {
  readonly id: BrickId;
  readonly kind: BrickKind;
  readonly name: string;
  readonly descriptor: ToolDescriptor;
  readonly origin: ToolOrigin;
  readonly policy: ToolPolicy;
  readonly scope: ForgeScope;
  readonly lifecycle: BrickLifecycle;
  readonly verificationReport: VerificationReport;
  readonly metadata: ForgeResultMetadata;
  /** Number of forge operations consumed. When onForgeConsumed is provided in ForgeDeps, incrementing is automatic; otherwise the caller must increment forgesThisSession by this amount. */
  readonly forgesConsumed: number;
}

// ---------------------------------------------------------------------------
// Verification report
// ---------------------------------------------------------------------------

export type VerificationStage = "static" | "format" | "resolve" | "sandbox" | "self_test" | "trust";

export interface StageReport {
  readonly stage: VerificationStage;
  readonly passed: boolean;
  readonly durationMs: number;
  readonly message?: string;
}

export interface ResolveStageReport extends StageReport {
  readonly stage: "resolve";
  /** Workspace path for bricks with npm dependencies, undefined if no packages. */
  readonly workspacePath?: string;
  /** Entry file path for the brick's implementation, undefined if no packages. */
  readonly entryPath?: string;
}

export interface TrustStageReport extends StageReport {
  readonly stage: "trust";
  readonly sandbox: boolean;
}

export interface SelfTestStageReport extends StageReport {
  readonly stage: "self_test";
  readonly testCasesRun: number;
  readonly agentProvidedCount: number;
  readonly autoGeneratedCount: number;
}

export interface VerificationReport {
  readonly stages: readonly StageReport[];
  readonly sandbox: boolean;
  readonly totalDurationMs: number;
  readonly passed: boolean;
}

// ---------------------------------------------------------------------------
// Forge inputs (discriminated union)
// ---------------------------------------------------------------------------

export type { TestCase } from "@koi/core";

/** Shared fields present on every forge input variant. */
export interface ForgeInputBase {
  readonly name: string;
  readonly description: string;
  readonly tags?: readonly string[];
  readonly files?: Readonly<Record<string, string>>;
  readonly requires?: BrickRequires;
  readonly classification?: DataClassification;
  readonly contentMarkers?: readonly ContentMarker[];
  /** Activation trigger patterns — natural language phrases declaring when this brick is relevant. */
  readonly trigger?: readonly string[];
  /** Parent brick this was evolved from. Undefined for original bricks. */
  readonly parentBrickId?: BrickId | undefined;
  /** How this brick was derived from its parent. */
  readonly evolutionKind?: EvolutionKind | undefined;
}

export interface ForgeToolInput extends ForgeInputBase {
  readonly kind: "tool";
  readonly inputSchema: Readonly<Record<string, unknown>>;
  readonly outputSchema?: Readonly<Record<string, unknown>> | undefined;
  readonly implementation: string;
  readonly testCases?: readonly TestCase[];
  readonly configSchema?: Readonly<Record<string, unknown>>;
}

export interface ForgeSkillInput extends ForgeInputBase {
  readonly kind: "skill";
  /** Markdown body of the skill (the raw content, not the generated SKILL.md). */
  readonly body: string;
  /** Optional JSON Schema for skill configuration (e.g., data source connection params). */
  readonly configSchema?: Readonly<Record<string, unknown>>;
}

export interface ForgeAgentInputWithManifest extends ForgeInputBase {
  readonly kind: "agent";
  readonly manifestYaml: string;
  readonly brickIds?: undefined;
}

export interface ForgeAgentInputWithBricks extends ForgeInputBase {
  readonly kind: "agent";
  readonly brickIds: readonly string[];
  readonly manifestYaml?: undefined;
  readonly model?: string;
  readonly agentType?: string;
}

export type ForgeAgentInput = ForgeAgentInputWithManifest | ForgeAgentInputWithBricks;

export interface ForgeMiddlewareInput extends ForgeInputBase {
  readonly kind: "middleware";
  readonly implementation: string;
  readonly testCases?: readonly TestCase[];
  readonly configSchema?: Readonly<Record<string, unknown>>;
}

export interface ForgeChannelInput extends ForgeInputBase {
  readonly kind: "channel";
  readonly implementation: string;
  readonly testCases?: readonly TestCase[];
  readonly configSchema?: Readonly<Record<string, unknown>>;
}

export interface ForgeCompositeInput extends ForgeInputBase {
  readonly kind: "composite";
  readonly brickIds: readonly string[];
}

export type ForgeInput =
  | ForgeToolInput
  | ForgeSkillInput
  | ForgeAgentInput
  | ForgeMiddlewareInput
  | ForgeChannelInput
  | ForgeCompositeInput;

// ---------------------------------------------------------------------------
// Pluggable verifier (Stage 3)
// ---------------------------------------------------------------------------

export interface VerifierResult {
  readonly passed: boolean;
  readonly message?: string;
}

export interface ForgeVerifier {
  readonly name: string;
  readonly verify: (input: ForgeInput, context: ForgeContext) => Promise<VerifierResult>;
}

// Sandbox executor — canonical definitions live in @koi/core (L0)
export type {
  SandboxError,
  SandboxErrorCode,
  SandboxExecutor,
  SandboxResult,
} from "@koi/core";

// ---------------------------------------------------------------------------
// Forge context
// ---------------------------------------------------------------------------

export interface ForgeContext {
  readonly agentId: string;
  readonly depth: number;
  readonly sessionId: string;
  readonly forgesThisSession: number;
  /** Zone identifier for zone-scoped brick visibility. */
  readonly zoneId?: string | undefined;
}

// Brick artifact types — canonical definitions live in @koi/core (L0)
export type {
  AgentArtifact,
  BrickArtifact,
  BrickArtifactBase,
  CompositeArtifact,
  ImplementationArtifact,
  SkillArtifact,
  ToolArtifact,
} from "@koi/core";

// ---------------------------------------------------------------------------
// Promote result (returned by promote_forge)
// ---------------------------------------------------------------------------

export interface PromoteChange<T> {
  readonly from: T;
  readonly to: T;
}

export interface PromoteResult {
  readonly brickId: BrickId;
  readonly applied: boolean;
  readonly requiresHumanApproval: boolean;
  readonly changes: {
    readonly scope?: PromoteChange<ForgeScope>;
    readonly policy?: PromoteChange<ToolPolicy>;
    readonly lifecycle?: PromoteChange<BrickLifecycle>;
  };
  readonly message?: string;
}

// ---------------------------------------------------------------------------
// Manifest parser (injected dependency — avoids L2 peer import of @koi/manifest)
// ---------------------------------------------------------------------------

export type ManifestParseResult =
  | { readonly ok: true; readonly warnings: readonly string[]; readonly engine?: unknown }
  | { readonly ok: false; readonly error: string };

export interface ManifestParser {
  readonly parse: (yaml: string) => ManifestParseResult | Promise<ManifestParseResult>;
}

// Forge query — canonical definition lives in @koi/core (L0)
export type { ForgeQuery } from "@koi/core";

// ---------------------------------------------------------------------------
// Governance result (used by governance checks and HITL decisions)
// ---------------------------------------------------------------------------

export interface GovernanceResult {
  readonly requiresHumanApproval: boolean;
  readonly message?: string;
}

// ---------------------------------------------------------------------------
// Drift checker types (extracted from drift-checker.ts)
// ---------------------------------------------------------------------------

import type { BrickDriftContext } from "@koi/core";

/** Result of a drift check — score + current commit for updating brick metadata. */
export interface DriftCheckResult {
  readonly driftScore: number;
  readonly currentCommit: string;
}

/** Dependency-injected drift detection — ForgeResolver calls this on load(). */
export interface DriftChecker {
  readonly checkDrift: (driftContext: BrickDriftContext) => Promise<DriftCheckResult | undefined>;
}

// ---------------------------------------------------------------------------
// ForgeDeps — DI interface for forge tool dependencies (promoted from forge-tools)
// ---------------------------------------------------------------------------

/** Options for delegating implementation to an external coding agent. */
export interface DelegateOptions {
  /** Model to use for the coding agent (e.g., "opus"). */
  readonly model?: string | undefined;
  /** Timeout per attempt in milliseconds. Default: 120,000 (2 min). */
  readonly timeoutMs?: number | undefined;
  /** Number of retries after failure. Default: 0 (no retries). */
  readonly retries?: number | undefined;
}

/** Shared dependency bag for all forge tools — injected by L3 bundle. */
export interface ForgeDeps {
  readonly store: ForgeStore;
  readonly executor: SandboxExecutor;
  readonly verifiers: readonly ForgeVerifier[];
  readonly config: ForgeConfig;
  readonly context: ForgeContext;
  /** Injected manifest parser — required only for forge_agent. Avoids L2 peer import of @koi/manifest. */
  readonly manifestParser?: ManifestParser;
  /** Optional notifier for cross-agent cache invalidation after store mutations. */
  readonly notifier?: StoreChangeNotifier;
  /** Optional signing backend for attestation. When provided, forged bricks get cryptographic signatures. */
  readonly signer?: SigningBackend;
  /** Optional governance controller for live-counter budget checks (bypasses static ForgeContext.forgesThisSession). */
  readonly controller?: GovernanceController;
  /** Called after a successful forge with the number of forges consumed. When provided, incrementing the session counter is automatic. */
  readonly onForgeConsumed?: (consumed: number) => void | Promise<void>;
  /** Optional engine resolver — resolves engine config from a manifest into an EngineAdapter. Used by forge_agent to auto-resolve engines during forge. */
  readonly engineResolver?: (
    engineConfig: unknown,
  ) => Promise<Result<EngineAdapter | undefined, KoiError>>;
  /** DI pipeline — tools use pipeline methods for cross-L2 calls (verify, governance, attestation). Wired by L3 bundle. */
  readonly pipeline?: ForgePipeline;
  /** Discovers an external coding agent by name. Injected by L3 consumer. */
  readonly discoverAgent?: (name: string) => Promise<Result<ExternalAgentDescriptor, KoiError>>;
  /** Spawns an external coding agent to produce implementation code. Injected by L3 consumer. */
  readonly spawnCodingAgent?: (
    agent: ExternalAgentDescriptor,
    prompt: string,
    options: DelegateOptions,
  ) => Promise<Result<string, KoiError>>;
  /** Optional hybrid retriever for semantic brick discovery (BM25+vector via Nexus Search). */
  readonly retriever?: Retriever | undefined;
  /** Optional error callback for non-fatal failures (notification errors, indexing errors). */
  readonly onError?: ((error: unknown) => void) | undefined;
}

import type { ForgeConfig } from "./config.js";
import type { ForgeError } from "./errors.js";
import type { ForgePipeline } from "./pipeline.js";

// ---------------------------------------------------------------------------
// ForgeRunner — DI type for cross-L2 forge pipeline invocation
// ---------------------------------------------------------------------------

/** Builder returns a BrickArtifact body without provenance. */
export type ArtifactBuilder = (
  report: VerificationReport,
  deps: ForgeDeps,
) => Omit<BrickArtifact, "provenance">;

/** Injectable forge pipeline runner — allows L2 packages to invoke the forge pipeline without importing forge-tools. */
export type ForgeRunner = (
  input: ForgeInput,
  deps: ForgeDeps,
  buildArtifact: ArtifactBuilder,
) => Promise<Result<ForgeResult, ForgeError>>;
