/**
 * Runtime fence preamble — installed at the head of Worker B (handler-runner)
 * before operator code is loaded. Overwrites every entry in
 * `RUNTIME_FENCE_TARGETS` with a throwing accessor so even dynamic
 * (`eval("fet" + "ch")`) reaches are stopped.
 *
 * Returned as a JS source string so the adapter can prepend it to the bundle
 * uploaded to Cloudflare. The string is content-addressable via its sha256 —
 * the deploy pipeline pins this hash in the attestation fingerprint.
 *
 * Only the top-level identifier forms are overwritten. Member-chain forms
 * (e.g. `WebAssembly.instantiate`) are still trapped because their parents
 * (`WebAssembly`) cannot be reached without first naming the global, and the
 * static scan flags any direct reference at deploy time.
 */

import { RUNTIME_FENCE_TARGETS, RUNTIME_FENCE_TOP_LEVEL_IDENTIFIERS } from "@koi/core";

const FENCE_FUNCTION_NAME = "__koiInstallRuntimeFence";

const buildOverwriteBlock = (): string => {
  const topLevelLines = RUNTIME_FENCE_TOP_LEVEL_IDENTIFIERS.map((name) => {
    return [
      `  try {`,
      `    Object.defineProperty(globalThis, ${JSON.stringify(name)}, {`,
      `      configurable: false, enumerable: false,`,
      `      get() { throw new Error("RUNTIME_FENCE: globalThis." + ${JSON.stringify(name)} + " is not allowed in class-A handlers"); },`,
      `    });`,
      `  } catch (_e) { /* already non-configurable on this runtime — earlier defineProperty stuck */ }`,
    ].join("\n");
  });
  // Member-chain forms (e.g. `WebAssembly.instantiate`, `navigator.sendBeacon`).
  // Both `globalThis.WebAssembly.instantiate` and `globalThis["WebAssembly"]["instantiate"]`
  // resolve through the same underlying property — overwriting the property on
  // the parent object closes the computed-access bypass that overwriting only
  // top-level identifiers would leave open.
  const memberLines = RUNTIME_FENCE_TARGETS.filter((t) => t.includes(".")).map((target) => {
    const dot = target.indexOf(".");
    const parent = target.slice(0, dot);
    const child = target.slice(dot + 1);
    return [
      `  try {`,
      `    var __p = globalThis[${JSON.stringify(parent)}];`,
      `    if (__p && typeof __p === "object") {`,
      `      Object.defineProperty(__p, ${JSON.stringify(child)}, {`,
      `        configurable: false, enumerable: false,`,
      `        get() { throw new Error("RUNTIME_FENCE: " + ${JSON.stringify(target)} + " is not allowed in class-A handlers"); },`,
      `      });`,
      `    }`,
      `  } catch (_e) { /* parent missing or property non-configurable — fence may be incomplete on this runtime */ }`,
    ].join("\n");
  });
  return [...topLevelLines, ...memberLines].join("\n");
};

/**
 * Idempotent fence-install JS source. Worker B prepends this to the bundle
 * and invokes the function exactly once before the first handler call.
 */
export const RUNTIME_FENCE_PREAMBLE_SOURCE: string = [
  `// koi-runtime-fence: installs throwing accessors on provider-mutable globals.`,
  `// Generated by @koi/sandbox-cloudflare. Do not edit by hand.`,
  `var ${FENCE_FUNCTION_NAME} = (function () {`,
  `  var installed = false;`,
  `  return function () {`,
  `    if (installed) return;`,
  `    installed = true;`,
  buildOverwriteBlock(),
  `  };`,
  `})();`,
  `${FENCE_FUNCTION_NAME}();`,
  ``,
].join("\n");

export const RUNTIME_FENCE_FUNCTION_NAME: string = FENCE_FUNCTION_NAME;
